config/routes.rb
Rails.application.routes.draw do


  root 'sessions#welcome'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#oauth_login'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get 'most_active_user' => 'users#most_active_user'
  get 'most_active_lab_member' => 'users#most_active_lab_member'
  get 'most_used' => 'reagents#most_used'
  get 'most_used_lab_reagent' => 'reagents#most_used_lab_reagent'

  resources :categories, only: [:index]
  resources :locations, only: [:show]
  resources :reagent_uses
  resources :reagents
  resources :reagents, only: [:show] do
    resources :reagent_uses, only: [:new, :create, :show]
  end
  resources :users

  #resources :labs
  resources :labs do
    get 'reagents/ask' => 'reagents#ask'
    get 'admin' => 'labs#admin'
    resources :reagents, only: [:index, :new, :create, :show]
    resources :categories, only: [:index, :show]
    resources :locations, only: [:index, :new, :create]
    resources :reagent_uses, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reagent.rb
class Reagent < ApplicationRecord
  belongs_to :lab
  belongs_to :location
  belongs_to :category
  has_many :reagent_uses
  has_many :users, through: :reagent_uses

  validates :name, :unit, :quantity, :source, :trigger, presence: true


  def category_attributes=(category_params)
    category = Category.find_or_create_by(category_params)
    self.category = category if category.valid?
  end

  scope :lab_reagents, -> (lab){Reagent.where(lab_id: lab.id)}
  scope :search_by_name, -> (search_name){where('lower(name) like ?', "%#{search_name.downcase}%")}
  scope :most_used, -> {Reagent.joins(:reagent_uses).group(:reagent_id).order("count(reagent_uses.reagent_id) desc").limit(1)}
  scope :most_used_lab_reagent, -> (lab){Reagent.joins(:reagent_uses).where(lab_id: lab.id).group(:reagent_id).order("count(reagent_uses.reagent_id) desc").limit(1)}

end

app/controllers/reagents_controller.rb
class ReagentsController < ApplicationController
  before_action :require_admin, only: [:new, :edit, :destroy]

  def most_used
    @reagents = Reagent.most_used
  end

  def most_used_lab_reagent
    lab = current_user.lab
    @reagents = Reagent.most_used_lab_reagent(lab)
  end

  def ask
    @lab = Lab.find_by_id(params[:lab_id])
    require_membership
    if params[:lab_id] && params[:name] != ""
      AdminMailer.with(user: current_user, lab: @lab, name: params[:name]).ask_email.deliver_now
      flash[:message] = "Your reagent request has been sent."
      redirect_to lab_path(@lab)
    else
      flash[:message] = "There was a problem with your reagent request."
      redirect_to lab_path(@lab)
    end
  end

  def index
    #only nested route
    if params[:lab_id] && @lab = Lab.find_by_id(params[:lab_id])
      require_membership
      if params[:name] == nil || params[:name] == ""
          @reagents = Reagent.lab_reagents(@lab)#@lab.reagents
      else
        @reagents = @lab.reagents.search_by_name(params[:name])
      end
    else
      flash[:message] = "That information is not available."
      redirect_to '/'
    end
  end

  def new
    if params[:lab_id] && @lab = Lab.find_by_id(params[:lab_id])
      require_membership
      @reagent = @lab.reagents.build
      @category = @reagent.build_category
    else
      flash[:message] = "New reagents must be associated with an existing lab. "
      redirect_to '/'
    end
  end

  def create
    if params[:lab_id] && @lab = Lab.find_by_id(params[:lab_id])
      @reagent = @lab.reagents.build(reagent_params)
    else
      @reagent = Reagent.new(reagent_params)
    end
    if @reagent.save
      redirect_to lab_reagent_path(@lab, @reagent)
    else
      render :new
    end
  end


  def show
    set_reagent_and_lab
    require_membership
  end

  def edit
    set_reagent
  end

  def update
    set_reagent
    if @reagent.update(reagent_params)
      redirect_to reagent_path(@reagent)
    else
      render :edit
    end
  end

  def destroy
    set_reagent_and_lab
    require_membership
    @reagent.destroy
    redirect_to lab_path(@lab)
  end



  private
  def reagent_params
    params.require(:reagent).permit(:lab_id, :name, :category_id, :source, :unit, :quantity, :trigger, :location_id, category_attributes:[:name])
  end

  def set_reagent
    @reagent = Reagent.find(params[:id])
  end

  def set_reagent_and_lab
    set_reagent
    @lab = Lab.find(@reagent.lab_id)
  end


end

app/helpers/reagents_helper.rb
module ReagentsHelper



end

app/views/reagents/_form.html.erb
<%= render partial: "layouts/errors", locals: { object: @reagent } %>

<%= form_for [@lab, @reagent] do |f| %>



   <%= f.label :name %>
   <%= f.text_field :name %>
   <br><br>
   <%= f.label :category_id, "Select category" %>
   <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
    <br><br>
    Or make a new category:
    <%= f.fields_for :category do |category| %>
      <%= category.label :name %>
      <%= category.text_field :name %>
    <% end %>

   <%= f.label :source %>
   <%= f.text_field :source %>
    <br><br>
   <%= f.label :unit%>
   <%= f.text_field :unit%>
    <br><br>
    <%= f.label :quantity%>
    <%= f.number_field :quantity, step: 0.1 %>
    <br><br>
    <%= f.label :trigger%>
    <%= f.number_field :trigger, step: 0.1 %>
    <br><br>
   <%= f.label :location_id, "Select location" %>
   <%= f.collection_select :location_id, Location.all, :id, :name %>


   <%= f.submit  %>

<% end %>

app/views/reagents/edit.html.erb
<%= render "form" %>

app/views/reagents/index.html.erb
<% if flash[:message] %>
  <div class="message"><%=flash[:message] %></div>
<% end %>
  <ul>
    <% #byebug %>
    <% @reagents.each do |reagent| %>
      <li>
        <%= link_to reagent.name, reagent_path(reagent) %> <br>
        Current amount: <%= reagent.quantity %>  <%= reagent.unit %> 
      </li>
    <% end %>
  </ul>

  <% if @reagents == [] %>
    <div ='container'>
    <%= "Sorry, #{@lab.principal_investigator} Lab does not have that reagent." %>
    </div>
    <br><br>
    <div = 'container'>
    <%= form_tag(lab_reagents_ask_path, method: "get") do %>
      <%= label_tag(:name, "Request reagent:") %>
      <%= text_field_tag(:name) %>
      <%= submit_tag("Submit") %>
    <% end %>
    <div/>
  <% end %>

app/views/reagents/most_used.html.erb
<% @reagents.each do |reagent| %>
     <%= reagent.name %>
     <% end %>

app/views/reagents/most_used_lab_reagent.html.erb
<% @reagents.each do |reagent| %>
     <%= reagent.name %>
  <% end %>

app/views/reagents/new.html.erb
<%= render "form" %>

app/views/reagents/search.html.erb
<h1>Reagent Search Form</h1>

<%= form_tag(lab_reagents_path, method: "get") do %>

<%= label_tag(:name, "Enter the name of the reagent") %>
<%= text_field_tag(:name) %>
<%= submit_tag("Search") %>
<% end %>

app/views/reagents/show.html.erb
  <% if flash[:message] %>
    <div class="message"><%=flash[:message] %></div>
  <% end %>

   Reagent: <%= @reagent.name %>
   <br><br>
   Current Amount: <%= @reagent.quantity%>  <%= @reagent.unit%>

    <br><br>
    Location: <%= @reagent.location.name%>


  <%= link_to "Go to this form to use this reagent:", new_reagent_reagent_use_path(@reagent) %>

  <% if @current_user.admin? %>
    <%= link_to "Edit this reagent", edit_reagent_path(@reagent) %>
  <% end %>

  <% if @current_user.admin? %>
    <%= link_to "Delete this reagent", reagent_path(@reagent), method: :delete %>
  <% end %>