config/routes.rb
Rails.application.routes.draw do


  root 'sessions#welcome'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#oauth_login'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get 'most_active_user' => 'users#most_active_user'
  get 'most_active_lab_member' => 'users#most_active_lab_member'
  get 'most_used' => 'reagents#most_used'
  get 'most_used_lab_reagent' => 'reagents#most_used_lab_reagent'

  resources :categories, only: [:index]
  resources :locations, only: [:show]
  resources :reagent_uses
  resources :reagents
  resources :reagents, only: [:show] do
    resources :reagent_uses, only: [:new, :create, :show]
  end
  resources :users

  #resources :labs
  resources :labs do
    get 'reagents/ask' => 'reagents#ask'
    get 'admin' => 'labs#admin'
    resources :reagents, only: [:index, :new, :create, :show]
    resources :categories, only: [:index, :show]
    resources :locations, only: [:index, :new, :create]
    resources :reagent_uses, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_many :users
  has_many :reagents
  has_many :locations
  has_many :reagent_uses

  validates :principal_investigator, :institution, presence: true
  validates :principal_investigator, uniqueness: { scope: :institution} #, message: "Institution already has a principal investigator with this name."}


  def admin_emails
    self.users.where(admin: true).pluck(:email)
  end

end

app/controllers/labs_controller.rb
class LabsController < ApplicationController

  before_action :require_admin, only: [:admin]

  def admin
    @lab = Lab.find(params[:lab_id])
    #byebug
    require_membership
  end

  def show
    @lab = Lab.find(params[:id])
    require_membership
  end

  private
  def lab_params
    params.require(:lab).permit(:principal_investigator, :institution)
  end



end

app/helpers/labs_helper.rb
module LabsHelper

  def category_array
    category_array = []
    @lab.reagents.each do |reagent|
      category_array << reagent.category
    end
    category_array.uniq
  end

end

app/views/labs/_admin.html.erb
<h2><%=link_to "See #{@lab.principal_investigator} Lab members", lab_users_path(@lab)%></h2>

<h2><%= link_to "Add a new reagent", new_lab_reagent_path(@lab) %></h2>

<h2><%= link_to "View reagent use registrations.", lab_reagent_uses_path(@lab) %></h2>

<h2><%= link_to "Create a new location", new_lab_location_path(@lab) %></h2>

<%= form_tag(lab_reagent_uses_path(@lab), method: "get") do %>

<h2><%= label_tag(:name, "View reagent use registrations by reagent name") %></h2>
<%= text_field_tag(:reagent) %>
<%= submit_tag("Reagent name") %>

<br><br>
<h2><%= label_tag(:user, "View reagent use records by consumer") %></h2>
<%= text_field_tag(:consumer) %>
<%= submit_tag("Consumer name") %>

<br><br>
<h2><%= label_tag(:user, "View reagent use records by date") %></h2>
<h3>Start date: <%= date_field_tag(:start_date) %> End date: <%= date_field_tag(:end_date) %></h3>
<%= submit_tag("Search by date") %>
<% end %>

app/views/labs/_home.html.erb
<h1>Welcome to the <%=@lab.principal_investigator%> Lab!</h1>
<br><br>
<h2><%= link_to "See all reagents", lab_reagents_path(@lab) %></h2>
<div class='container'>
<h2>Find reagents by category:</h2>
<ul>
<% category_array.each do |category| %>
  <li>
    <% @category = category %>
    <%= link_to @category.name, lab_category_path(@lab, @category) %>
    </li>
  <% end %>
  </ul>
</div>
<br><br>
<%= form_tag(lab_reagents_path(@lab), method: "get") do %>

<h2><%= label_tag(:name, "Search for a reagent by name") %></h2>
<%= text_field_tag(:name) %>
<%= submit_tag("Search") %>
<% end %>
<br><br>

<h2><%= link_to "See reagents by Location", lab_locations_path(@lab) %></h2>
<br><br>
<h2><%= link_to "View your reagent use records", user_path(@current_user.id) %></h2>

<h2><%= link_to "See most active user", most_active_user_path %></h2>

<h2><%= link_to "See most active lab member", most_active_lab_member_path %></h2>

<h2><%= link_to "See most used reagent", most_used_path %></h2>

<h2><%= link_to "See most used reagent for this lab", most_used_lab_reagent_path %></h2>

app/views/labs/admin.html.erb
<h2><%=link_to "See #{@lab.principal_investigator} Lab members", lab_users_path(@lab)%></h2>



<h2><%= link_to "Add a new reagent", new_lab_reagent_path(@lab) %></h2>

<h2><%= link_to "View reagent use records.", lab_reagent_uses_path(@lab) %></h2>

<h2><%= link_to "Create a new location", new_lab_location_path(@lab) %></h2>

<%= form_tag(lab_reagent_uses_path(@lab), method: "get") do %>

<h2><%= label_tag(:name, "View reagent use records by reagent name") %></h2>
<%= text_field_tag(:reagent) %>
<%= submit_tag("Reagent name") %>

<br><br>
<h2><%= label_tag(:consumer, "View reagent use records by user") %></h2>
<%= text_field_tag(:consumer) %>
<%= submit_tag("User name") %>

<br><br>
<h2><%= label_tag(:user, "View reagent use records by date") %></h2>
<h3>Start date: <%= date_field_tag(:start_date) %> End date: <%= date_field_tag(:end_date) %></h3>
<%= submit_tag("Search by date") %>
<% end %>

app/views/labs/show.html.erb
<% if flash[:message] %>
  <div class="message"><%=flash[:message] %></div>
<% end %>
<% @user = User.find(session[:user_id]) %>

<% if @lab.users.include?(@user) %>
  <%= render partial: 'home' %>
<% end %>