config/routes.rb
Rails.application.routes.draw do


  root 'sessions#welcome'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#oauth_login'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get 'most_active_user' => 'users#most_active_user'
  get 'most_active_lab_member' => 'users#most_active_lab_member'
  get 'most_used' => 'reagents#most_used'
  get 'most_used_lab_reagent' => 'reagents#most_used_lab_reagent'

  resources :categories, only: [:index]
  resources :locations, only: [:show]
  resources :reagent_uses
  resources :reagents
  resources :reagents, only: [:show] do
    resources :reagent_uses, only: [:new, :create, :show]
  end
  resources :users

  #resources :labs
  resources :labs do
    get 'reagents/ask' => 'reagents#ask'
    get 'admin' => 'labs#admin'
    resources :reagents, only: [:index, :new, :create, :show]
    resources :categories, only: [:index, :show]
    resources :locations, only: [:index, :new, :create]
    resources :reagent_uses, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :lab
  has_many :reagents

  validates :name, presence: true
  validates :name, uniqueness: { scope: :lab_id, message: "Lab already has this location."}


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    #only nested route
    if params[:lab_id] && @lab = Lab.find_by_id(params[:lab_id])
      @locations = @lab.locations
    end
  end

  def new
    #nested route
    if params[:lab_id] && @lab = Lab.find_by_id(params[:lab_id])
      @location = @lab.locations.build
    else
      flash[:message] = "Location must be associated with a lab."
      redirect_to '/'
    end
  end

  def create
    if params[:lab_id] && @lab = Lab.find_by_id(params[:lab_id])
      @location = @lab.locations.build(location_params)
    end
    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  private
  def location_params
    params.require(:location).permit(:name, :lab_id)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/index.html.erb
<h1>Reagents for the <%=@lab.principal_investigator%> Lab are stored in these locations:

    <ul>
    <% @locations.each do |location| %>
      <li>
        <%= link_to location.name, location_path(location) %><br>

    <% end %>
      </li>

    </ul>
<h1> Click on the link to see the reagents at each location </h1>

app/views/locations/new.html.erb
<%= render partial: "layouts/errors", locals: { object: @location } %>

<%= form_for [@lab, @location] do |f| %>



   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.submit "Create Location" %>

<% end %>

app/views/locations/show.html.erb
<h1>Reagents stored in the <%=@location.name%>: </h1>
    <ul>
    <% @location.reagents.each do |reagent| %>
      <li>

          <%= link_to reagent.name, reagent_path(reagent) %> <br>

    <% end %>
      </li>

    </ul>
<h1>Click on the reagent you want information about</h1>