config/routes.rb
Rails.application.routes.draw do


  root 'sessions#welcome'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#oauth_login'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get 'most_active_user' => 'users#most_active_user'
  get 'most_active_lab_member' => 'users#most_active_lab_member'
  get 'most_used' => 'reagents#most_used'
  get 'most_used_lab_reagent' => 'reagents#most_used_lab_reagent'

  resources :categories, only: [:index]
  resources :locations, only: [:show]
  resources :reagent_uses
  resources :reagents
  resources :reagents, only: [:show] do
    resources :reagent_uses, only: [:new, :create, :show]
  end
  resources :users

  #resources :labs
  resources :labs do
    get 'reagents/ask' => 'reagents#ask'
    get 'admin' => 'labs#admin'
    resources :reagents, only: [:index, :new, :create, :show]
    resources :categories, only: [:index, :show]
    resources :locations, only: [:index, :new, :create]
    resources :reagent_uses, only: [:index]
    resources :users, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object %>
  <% if object.errors.any? %>
    <div id="error_explanation">


      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabSupplyTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class='navbar'>
    <% if logged_in %>
      <%= link_to "Log out", logout_path, method: :delete, class:'button' %>
      <%= go_home %>
        <% if @current_user.admin %>
          <%= link_to "Admin Functions", lab_admin_path(@lab) %>
        <% end %>
    <% end %>
    <div class='container'>
    <%= yield %>
    </div>
  </body>
</html>